id: 7bd628de2c4545c0a1f53c3c780a6a99
initial_creation_type: ocr
source_metadata:
  volumes:
    d08723cbe5ea4d7aaf50ec01eb0386f4:
      base_file: v057.txt
      image_group_id: I1PD95903
      title: ''
      total_pages: 1649
      volume_number: 58
